/**
 * Zoolu API
 * Zoolu API Documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountFilesDTO } from './accountFilesDTO';
import { CompanyDTO } from './companyDTO';
import { DriverLocationDTO } from './driverLocationDTO';
import { GenderDTO } from './genderDTO';
import { LanguageDTO } from './languageDTO';
import { TrailerDTO } from './models';
import { NotificationDTO } from './notificationDTO';
import { RoleDTO } from './roleDTO';
import { TruckDTO } from './truckDTO';

export interface AccountDTO {
  id: number;
  email: string;
  companyId: number;
  roleId: number;
  firstName: string;
  lastName: string;
  role?: RoleDTO;
  blocked: boolean;
  deleted: boolean;
  approved: boolean;
  company?: CompanyDTO;
  avatarUrl: string;
  address: string;
  city: string;
  dlNumber: string;
  emailConfirmed: boolean;
  gender: GenderDTO;
  genderId: number;
  receiveNotifications: boolean;
  state: string;
  signatureUrl?: string;
  zip: string;
  dispatcher?: AccountDTO;
  truck?: TruckDTO;
  trailer?: TrailerDTO;
  files?: AccountFilesDTO[];
  languages?: LanguageDTO[];
  phoneNumber?: string;
  locations?: DriverLocationDTO[];
  payRate?: number;
  companyName?: string;
  notifications?: NotificationDTO[];
  notificationOrders?: number;
  notificationCompanies?: number;
  notificationUsers?: number;
  notificationQuotes?: number;
}
