/**
 * Zoolu API
 * Zoolu API Documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CarrierRegisterRequest {
  hash: string;
  name: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  dotNumber: string;
  msNumber: string;
  officePhone: string;
  contactPersonFirstName: string;
  contactPersonLastName: string;
  contactPersonPhone?: string;
  mcCertificateUrl: string;
  insuranceUrl: string;
  token: string;
}
