/**
 * Zoolu API
 * Zoolu API Documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountDTO } from './accountDTO';
import { CompanyDTO } from './companyDTO';
import { InviteStatusDTO } from './inviteStatusDTO';
import { NotificationDTO } from './models';
import { RoleDTO } from './roleDTO';

export interface InviteDTO {
  id: number;
  hash: string;
  email: string;
  roleId: number;
  role?: RoleDTO;
  company?: CompanyDTO;
  companyId: number;
  extended: boolean;
  expire: Date;
  firstName: string;
  lastName: string;
  createdById: number;
  createdBy?: AccountDTO;
  statusId: number;
  status?: InviteStatusDTO;
  createdAt?: Date;
  notifications?: NotificationDTO[];
}
